version: '3.8'

services:
  storeapi:
    build:
      context: .
      dockerfile: Dockerfile.storeapi
    ports:
      - 5066:5066
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5066
    depends_on:
      - storedb

  storedb:
    build: 
      context: .
      dockerfile: Dockerfile.storedb
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql:/var/opt/mssql

volumes:
  storedb-data:
