# Use the official SQL Server 2022 Linux image from Microsoft
FROM mcr.microsoft.com/mssql/server:2022-latest

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=@dm1n123
ENV MSSQL_PID=Developer

# Copy the database initialization script into the docker image
COPY ./db-init.sql /docker-entrypoint-initdb.d/

# Run the initialization script at startup
RUN /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "@dm1n123" -d master -i /docker-entrypoint-initdb.d/db-init.sql
